### ISSUE TITLE
[Task] 이메일 회원가입 -판매회원 구현 

### ISSUE THREAD

**Issue by lvest** [codestates/comong#11]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 이메일 회원가입 -판매회원 구현 

### TODO
1. [ ] 판매 정보 템플릿 작성
2. [ ] 카테고리 컴포넌트 구현
3. [ ] 주소 검색 api로 주소 받아오기
4. [ ] 회원가입 기능 구현
