### ISSUE TITLE
[Task] nestjs 프레임워크를 이용해 백엔드 프로젝트 생성

### ISSUE THREAD

**Issue by dahyeon11** [codestates/comong#18]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: [Task] nestjs 프레임워크를 이용해 백엔드 프로젝트 생성

### TODO
1. [ ] nestjs 초기환경 구성
2. [ ] 기초적인 폴더 구조 생성
3. [ ] 미들웨어 구성
4. [ ] 모듈, 컨트롤러, 서비스 생성

### Estimated time
> Pick one
`3h`

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
