### ISSUE TITLE
[Task] 이메일 회원가입 공통 사항 구현

### ISSUE THREAD

**Issue by lvest** [codestates/comong#5]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 이메일 회원가입 공통 사항 구현

### TODO
1. [ ] Nested Routes로 일반회원, 판매회원 분할
2. [ ] 기본정보에 해당하는 템플릿 작성
3. [ ] 이메일 중복 검사
4. [ ] 비밀번호 유효성 검사
