### ISSUE TITLE
[Task] 이메일 회원가입 - 일반회원  구현

### ISSUE THREAD

**Issue by lvest** [codestates/comong#9]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 이메일 회원가입 - 일반회원  구현

### TODO
1. [ ] 추가 정보 템플릿 작성
2. [ ] 일반회원 회원가입 기능 구현
3. [ ] 관심사 - 인터렉티브하게 구현하기 (Optional)
